// <auto-generated />
namespace InventoryManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WeeklyReport1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WeeklyReport1));
        
        string IMigrationMetadata.Id
        {
            get { return "201708252245370_WeeklyReport1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
